package com.buddhism.model;
// Generated 2012-7-1 3:41:49 by Hibernate Tools 3.2.1.GA



/**
 * Media generated by hbm2java
 */
public class Media  implements java.io.Serializable {


     private Integer id;
     private Post post;
     private Packet packet;
     private String mediaUrl;
     private short mediaType;

    public Media() {
    }

    public Media(Post post, Packet packet, String mediaUrl, short mediaType) {
       this.post = post;
       this.packet = packet;
       this.mediaUrl = mediaUrl;
       this.mediaType = mediaType;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Post getPost() {
        return this.post;
    }
    
    public void setPost(Post post) {
        this.post = post;
    }
    public Packet getPacket() {
        return this.packet;
    }
    
    public void setPacket(Packet packet) {
        this.packet = packet;
    }
    public String getMediaUrl() {
        return this.mediaUrl;
    }
    
    public void setMediaUrl(String mediaUrl) {
        this.mediaUrl = mediaUrl;
    }
    public short getMediaType() {
        return this.mediaType;
    }
    
    public void setMediaType(short mediaType) {
        this.mediaType = mediaType;
    }




}


