package com.buddhism.model;
// Generated 2012-7-6 23:08:08 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Packet generated by hbm2java
 */
public class Packet  implements java.io.Serializable {


     private Short id;
     private String packetTitle;
     private Date packetDate;
     private String packetFirst;
     private short packetType;
     private Set<Media> medias = new HashSet<Media>(0);

    public Packet() {
    }

	
    public Packet(String packetTitle, Date packetDate, String packetFirst, short packetType) {
        this.packetTitle = packetTitle;
        this.packetDate = packetDate;
        this.packetFirst = packetFirst;
        this.packetType = packetType;
    }
    public Packet(String packetTitle, Date packetDate, String packetFirst, short packetType, Set<Media> medias) {
       this.packetTitle = packetTitle;
       this.packetDate = packetDate;
       this.packetFirst = packetFirst;
       this.packetType = packetType;
       this.medias = medias;
    }
   
    public Short getId() {
        return this.id;
    }
    
    public void setId(Short id) {
        this.id = id;
    }
    public String getPacketTitle() {
        return this.packetTitle;
    }
    
    public void setPacketTitle(String packetTitle) {
        this.packetTitle = packetTitle;
    }
    public Date getPacketDate() {
        return this.packetDate;
    }
    
    public void setPacketDate(Date packetDate) {
        this.packetDate = packetDate;
    }
    public String getPacketFirst() {
        return this.packetFirst;
    }
    
    public void setPacketFirst(String packetFirst) {
        this.packetFirst = packetFirst;
    }
    public short getPacketType() {
        return this.packetType;
    }
    
    public void setPacketType(short packetType) {
        this.packetType = packetType;
    }
    public Set<Media> getMedias() {
        return this.medias;
    }
    
    public void setMedias(Set<Media> medias) {
        this.medias = medias;
    }




}


